# Generated by Django 3.2.12 on 2022-02-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='changed_by',
        ),
        migrations.AlterField(
            model_name='historicalchoice',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalpollwithextrafields',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
